version: '3.8'

services:
  # Conteneur 1 : Base de données
  mariadb_db:
    image: mariadb:latest
    container_name: health_check_360_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_securise
      MYSQL_DATABASE: health_check_360_db
      MYSQL_USER: user_app
      MYSQL_PASSWORD: user_password_securise
    ports:
      - "3308:3306" # On mappe sur 3307 pour éviter les conflits si vous avez déjà MariaDB localement
    volumes:
      - ./mariadb_data:/var/lib/mysql            # Sauvegarde des données
      - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql # L'automatisation

  # Conteneur 2 : Backend (API)
  backend_api:
    build: ./backend_api
    container_name: health_check_360_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mariadb_db
    environment:
      DB_HOST: mariadb_db # Le nom du service ci-dessus sert d'adresse IP
      DB_USER: user_app
      DB_PASSWORD: user_password_securise
      DB_NAME: health_check_360_db
      PORT: 5000

  # Conteneur 3 : Frontend (Interface Utilisateur)
  frontend_app:
    build: ./frontend_app
    container_name: health_check_360_frontend
    restart: always
    ports:
      - "3000:3000" # Les utilisateurs accéderont via http://IP_SERVEUR:3000
    depends_on:
      - backend_api
    environment:
      # Pour que le front sache où taper (l'URL sera celle du navigateur client)
      VITE_API_URL: http://localhost:5000